### ISSUE TITLE
A02 Vignette Error

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/SOUNDBoard#2]
Hi Martin @mtmorgan, 
I was running the code in the vignette and it seems like the recent changes to `BiocFileCache` have broken it?

https://github.com/Bioconductor/SOUNDBoard/blob/master/vignettes/A02-tour.Rmd#approximate-output

In the "Demonstrating plot (ggplot2 / plotly) management" chunk, `sbreport` is not working because it can't find the relative path: 

```
 Error in value[[3L]](cond) : 
'RDSWidget' cannot load resource:
  cannot open the connection In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '54096cf1f71c', probable reason 'No such file or directory'
```

**Comment by mtmorgan** [comment]
hopefully fixed with https://github.com/Bioconductor/SOUNDBoard/commit/9c7230bf3f01928e9474cb85579454085b46b784
